import Link from 'next/link'
import './globals.scss'
import { Inter } from 'next/font/google'
// import { getProjects } from '../../sanity/sanity-utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const projects = await getProjects();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
